import { QuestionSeed } from '../types';

export const computerScience: QuestionSeed[] = [
  {
    id: 'cs-fund-1',
    category: 'Computer Science Fundamentals',
    text: 'What does HTML stand for?',
    answers: [
      { text: 'HyperText Markup Language', isCorrect: true },
      { text: 'High-Level Text Markup Language', isCorrect: false },
      { text: 'Hyperlink and Text Markup Language', isCorrect: false },
      { text: 'Home Tool Markup Language', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'web'],
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'cs-fund-2',
    category: 'Computer Science Fundamentals',
    text: 'What is the time complexity of binary search?',
    answers: [
      { text: 'O(n)', isCorrect: false },
      { text: 'O(log n)', isCorrect: true },
      { text: 'O(n²)', isCorrect: false },
      { text: 'O(1)', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'algorithms', 'complexity'],
    createdAt: new Date('2024-02-11'),
  },
  {
    id: 'cs-fund-3',
    category: 'Computer Science Fundamentals',
    text: 'What is a variable that stores a memory address called?',
    answers: [
      { text: 'Array', isCorrect: false },
      { text: 'Pointer', isCorrect: true },
      { text: 'Reference', isCorrect: false },
      { text: 'Index', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'memory'],
    createdAt: new Date('2024-02-12'),
  },
  {
    id: 'cs-fund-4',
    category: 'Computer Science Fundamentals',
    text: 'What does API stand for?',
    answers: [
      { text: 'Application Programming Interface', isCorrect: true },
      { text: 'Automated Program Integration', isCorrect: false },
      { text: 'Advanced Programming Interface', isCorrect: false },
      { text: 'Application Process Integration', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'api'],
    createdAt: new Date('2024-02-13'),
  },
  {
    id: 'cs-fund-5',
    category: 'Computer Science Fundamentals',
    text: 'Which data structure follows LIFO (Last In First Out) principle?',
    answers: [
      { text: 'Queue', isCorrect: false },
      { text: 'Stack', isCorrect: true },
      { text: 'Array', isCorrect: false },
      { text: 'Linked List', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'data-structures'],
    createdAt: new Date('2024-02-14'),
  },
  {
    id: 'cs-fund-6',
    category: 'Computer Science Fundamentals',
    text: 'What is the time complexity of quicksort in the average case?',
    answers: [
      { text: 'O(n)', isCorrect: false },
      { text: 'O(n log n)', isCorrect: true },
      { text: 'O(n²)', isCorrect: false },
      { text: 'O(log n)', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'algorithms', 'sorting', 'complexity'],
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'cs-fund-7',
    category: 'Computer Science Fundamentals',
    text: 'What does CPU stand for?',
    answers: [
      { text: 'Central Processing Unit', isCorrect: true },
      { text: 'Computer Processing Unit', isCorrect: false },
      { text: 'Central Program Unit', isCorrect: false },
      { text: 'Computer Program Unit', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'hardware'],
    createdAt: new Date('2024-02-16'),
  },
  {
    id: 'cs-fund-8',
    category: 'Computer Science Fundamentals',
    text: 'Which data structure follows FIFO (First In First Out) principle?',
    answers: [
      { text: 'Stack', isCorrect: false },
      { text: 'Queue', isCorrect: true },
      { text: 'Tree', isCorrect: false },
      { text: 'Graph', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'data-structures'],
    createdAt: new Date('2024-02-17'),
  },
  {
    id: 'cs-fund-9',
    category: 'Computer Science Fundamentals',
    text: 'What is the primary purpose of an operating system?',
    answers: [
      { text: 'To run applications', isCorrect: false },
      { text: 'To manage hardware resources and provide services', isCorrect: true },
      { text: 'To store data', isCorrect: false },
      { text: 'To connect to the internet', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'operating-systems'],
    createdAt: new Date('2024-02-18'),
  },
  {
    id: 'cs-fund-10',
    category: 'Computer Science Fundamentals',
    text: 'What does SQL stand for?',
    answers: [
      { text: 'Structured Query Language', isCorrect: true },
      { text: 'Simple Query Language', isCorrect: false },
      { text: 'Standard Query Language', isCorrect: false },
      { text: 'System Query Language', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'databases', 'sql'],
    createdAt: new Date('2024-02-19'),
  },
  {
    id: 'cs-fund-11',
    category: 'Computer Science Fundamentals',
    text: 'What is recursion?',
    answers: [
      { text: 'A loop that runs forever', isCorrect: false },
      { text: 'A function that calls itself', isCorrect: true },
      { text: 'A data structure', isCorrect: false },
      { text: 'A sorting algorithm', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'programming', 'recursion'],
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'cs-fund-12',
    category: 'Computer Science Fundamentals',
    text: 'What is the time complexity of accessing an element in an array by index?',
    answers: [
      { text: 'O(n)', isCorrect: false },
      { text: 'O(1)', isCorrect: true },
      { text: 'O(log n)', isCorrect: false },
      { text: 'O(n²)', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'data-structures', 'complexity'],
    createdAt: new Date('2024-02-21'),
  },
  {
    id: 'cs-fund-13',
    category: 'Computer Science Fundamentals',
    text: 'What does HTTP stand for?',
    answers: [
      { text: 'HyperText Transfer Protocol', isCorrect: true },
      { text: 'High-Level Text Transfer Protocol', isCorrect: false },
      { text: 'Hyperlink Text Transfer Protocol', isCorrect: false },
      { text: 'Home Tool Transfer Protocol', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'networking', 'web'],
    createdAt: new Date('2024-02-22'),
  },
  {
    id: 'cs-fund-14',
    category: 'Computer Science Fundamentals',
    text: 'What is a hash table?',
    answers: [
      { text: 'A sorted array', isCorrect: false },
      { text: 'A data structure that maps keys to values using a hash function', isCorrect: true },
      { text: 'A type of tree', isCorrect: false },
      { text: 'A linked list', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'data-structures', 'hash-table'],
    createdAt: new Date('2024-02-23'),
  },
  {
    id: 'cs-fund-15',
    category: 'Computer Science Fundamentals',
    text: 'What is the difference between a compiler and an interpreter?',
    answers: [
      { text: 'A compiler translates code before execution, an interpreter executes code line by line', isCorrect: true },
      { text: 'They are the same thing', isCorrect: false },
      { text: 'A compiler is faster than an interpreter', isCorrect: false },
      { text: 'An interpreter is only for web development', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'programming', 'compilers'],
    createdAt: new Date('2024-02-24'),
  },
  {
    id: 'cs-fund-16',
    category: 'Computer Science Fundamentals',
    text: 'What is object-oriented programming (OOP)?',
    answers: [
      { text: 'A programming paradigm based on objects and classes', isCorrect: true },
      { text: 'A type of database', isCorrect: false },
      { text: 'A sorting algorithm', isCorrect: false },
      { text: 'A network protocol', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'programming', 'oop'],
    createdAt: new Date('2024-02-25'),
  },
  {
    id: 'cs-fund-17',
    category: 'Computer Science Fundamentals',
    text: 'What is the time complexity of linear search?',
    answers: [
      { text: 'O(1)', isCorrect: false },
      { text: 'O(n)', isCorrect: true },
      { text: 'O(log n)', isCorrect: false },
      { text: 'O(n²)', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'algorithms', 'searching', 'complexity'],
    createdAt: new Date('2024-02-26'),
  },
  {
    id: 'cs-fund-18',
    category: 'Computer Science Fundamentals',
    text: 'What is a database index?',
    answers: [
      { text: 'A backup of the database', isCorrect: false },
      { text: 'A data structure that improves the speed of data retrieval', isCorrect: true },
      { text: 'A type of query', isCorrect: false },
      { text: 'A security feature', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'databases'],
    createdAt: new Date('2024-02-27'),
  },
  {
    id: 'cs-fund-19',
    category: 'Computer Science Fundamentals',
    text: 'What does DNS stand for?',
    answers: [
      { text: 'Domain Name System', isCorrect: true },
      { text: 'Dynamic Network System', isCorrect: false },
      { text: 'Data Network Service', isCorrect: false },
      { text: 'Digital Name Server', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'networking', 'dns'],
    createdAt: new Date('2024-02-28'),
  },
  {
    id: 'cs-fund-20',
    category: 'Computer Science Fundamentals',
    text: 'What is a binary tree?',
    answers: [
      { text: 'A tree with exactly two nodes', isCorrect: false },
      { text: 'A tree data structure where each node has at most two children', isCorrect: true },
      { text: 'A tree that stores binary data', isCorrect: false },
      { text: 'A tree with two roots', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'data-structures', 'trees'],
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'cs-fund-21',
    category: 'Computer Science Fundamentals',
    text: 'What is the difference between RAM and ROM?',
    answers: [
      { text: 'RAM is volatile and temporary, ROM is non-volatile and permanent', isCorrect: true },
      { text: 'RAM is slower than ROM', isCorrect: false },
      { text: 'ROM is used for running programs', isCorrect: false },
      { text: 'They are the same thing', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'hardware', 'memory'],
    createdAt: new Date('2024-03-02'),
  },
  {
    id: 'cs-fund-22',
    category: 'Computer Science Fundamentals',
    text: 'What is a thread in programming?',
    answers: [
      { text: 'A type of data structure', isCorrect: false },
      { text: 'A sequence of executable instructions that can run concurrently', isCorrect: true },
      { text: 'A string variable', isCorrect: false },
      { text: 'A network connection', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'programming', 'concurrency'],
    createdAt: new Date('2024-03-03'),
  },
  {
    id: 'cs-fund-23',
    category: 'Computer Science Fundamentals',
    text: 'What is the purpose of a cache?',
    answers: [
      { text: 'To store deleted files', isCorrect: false },
      { text: 'To temporarily store frequently accessed data for faster retrieval', isCorrect: true },
      { text: 'To compress files', isCorrect: false },
      { text: 'To encrypt data', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'memory', 'performance'],
    createdAt: new Date('2024-03-04'),
  },
  {
    id: 'cs-fund-24',
    category: 'Computer Science Fundamentals',
    text: 'What is a stack overflow?',
    answers: [
      { text: 'A website for programmers', isCorrect: false },
      { text: 'An error that occurs when the stack exceeds its allocated memory', isCorrect: true },
      { text: 'A type of buffer', isCorrect: false },
      { text: 'A network error', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'programming', 'errors', 'memory'],
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'cs-fund-25',
    category: 'Computer Science Fundamentals',
    text: 'What is the difference between TCP and UDP?',
    answers: [
      { text: 'TCP is connection-oriented and reliable, UDP is connectionless and faster', isCorrect: true },
      { text: 'TCP is only for web, UDP is only for email', isCorrect: false },
      { text: 'TCP is slower than UDP', isCorrect: false },
      { text: 'They are the same protocol', isCorrect: false },
    ],
    tags: ['computer-science', 'fundamentals', 'networking', 'protocols'],
    createdAt: new Date('2024-03-06'),
  },
];
