import { QuestionSeed } from '../types';

export const historyWWII: QuestionSeed[] = [
  {
    id: 'hist-ww2-1',
    category: 'History World War II',
    text: 'In which year did World War II end?',
    answers: [
      { text: '1944', isCorrect: false },
      { text: '1945', isCorrect: true },
      { text: '1946', isCorrect: false },
      { text: '1947', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii'],
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'hist-ww2-2',
    category: 'History World War II',
    text: 'Which event is considered the start of World War II in Europe?',
    answers: [
      { text: 'Invasion of Poland', isCorrect: true },
      { text: 'Attack on Pearl Harbor', isCorrect: false },
      { text: 'Battle of Britain', isCorrect: false },
      { text: 'D-Day', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'europe'],
    createdAt: new Date('2024-02-16'),
  },
  {
    id: 'hist-ww2-3',
    category: 'History World War II',
    text: 'Who was the leader of Nazi Germany during World War II?',
    answers: [
      { text: 'Benito Mussolini', isCorrect: false },
      { text: 'Adolf Hitler', isCorrect: true },
      { text: 'Joseph Stalin', isCorrect: false },
      { text: 'Winston Churchill', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'leaders'],
    createdAt: new Date('2024-02-17'),
  },
  {
    id: 'hist-ww2-4',
    category: 'History World War II',
    text: 'Which battle is considered the turning point of World War II in the Pacific?',
    answers: [
      { text: 'Battle of Midway', isCorrect: true },
      { text: 'Battle of Guadalcanal', isCorrect: false },
      { text: 'Battle of Iwo Jima', isCorrect: false },
      { text: 'Battle of Okinawa', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'pacific'],
    createdAt: new Date('2024-02-18'),
  },
  {
    id: 'hist-ww2-5',
    category: 'History World War II',
    text: 'On which date did the attack on Pearl Harbor occur?',
    answers: [
      { text: 'December 7, 1941', isCorrect: true },
      { text: 'December 8, 1941', isCorrect: false },
      { text: 'November 7, 1941', isCorrect: false },
      { text: 'January 7, 1942', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'pacific', 'pearl-harbor'],
    createdAt: new Date('2024-02-19'),
  },
  {
    id: 'hist-ww2-6',
    category: 'History World War II',
    text: 'Which operation was the code name for the D-Day landings in Normandy?',
    answers: [
      { text: 'Operation Overlord', isCorrect: true },
      { text: 'Operation Barbarossa', isCorrect: false },
      { text: 'Operation Market Garden', isCorrect: false },
      { text: 'Operation Torch', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'd-day', 'normandy'],
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'hist-ww2-7',
    category: 'History World War II',
    text: 'Which country was invaded by Germany in Operation Barbarossa?',
    answers: [
      { text: 'Soviet Union', isCorrect: true },
      { text: 'Poland', isCorrect: false },
      { text: 'France', isCorrect: false },
      { text: 'United Kingdom', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'eastern-front', 'operation-barbarossa'],
    createdAt: new Date('2024-02-21'),
  },
  {
    id: 'hist-ww2-8',
    category: 'History World War II',
    text: 'What was the name of the systematic persecution and murder of six million Jews by Nazi Germany?',
    answers: [
      { text: 'The Holocaust', isCorrect: true },
      { text: 'The Final Solution', isCorrect: false },
      { text: 'Kristallnacht', isCorrect: false },
      { text: 'The Nuremberg Laws', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'holocaust'],
    createdAt: new Date('2024-02-22'),
  },
  {
    id: 'hist-ww2-9',
    category: 'History World War II',
    text: 'Which battle was the largest tank battle in history?',
    answers: [
      { text: 'Battle of Kursk', isCorrect: true },
      { text: 'Battle of Stalingrad', isCorrect: false },
      { text: 'Battle of the Bulge', isCorrect: false },
      { text: 'Battle of El Alamein', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'eastern-front', 'battles'],
    createdAt: new Date('2024-02-23'),
  },
  {
    id: 'hist-ww2-10',
    category: 'History World War II',
    text: 'Who was the Prime Minister of the United Kingdom for most of World War II?',
    answers: [
      { text: 'Winston Churchill', isCorrect: true },
      { text: 'Neville Chamberlain', isCorrect: false },
      { text: 'Clement Attlee', isCorrect: false },
      { text: 'Anthony Eden', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'leaders', 'united-kingdom'],
    createdAt: new Date('2024-02-24'),
  },
  {
    id: 'hist-ww2-11',
    category: 'History World War II',
    text: 'In which year did the United States enter World War II?',
    answers: [
      { text: '1941', isCorrect: true },
      { text: '1939', isCorrect: false },
      { text: '1940', isCorrect: false },
      { text: '1942', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'united-states'],
    createdAt: new Date('2024-02-25'),
  },
  {
    id: 'hist-ww2-12',
    category: 'History World War II',
    text: 'Which Japanese cities were targeted by atomic bombs in August 1945?',
    answers: [
      { text: 'Hiroshima and Nagasaki', isCorrect: true },
      { text: 'Tokyo and Osaka', isCorrect: false },
      { text: 'Kyoto and Yokohama', isCorrect: false },
      { text: 'Nagasaki and Tokyo', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'pacific', 'atomic-bomb'],
    createdAt: new Date('2024-02-26'),
  },
  {
    id: 'hist-ww2-13',
    category: 'History World War II',
    text: 'What was the name of the German air force during World War II?',
    answers: [
      { text: 'Luftwaffe', isCorrect: true },
      { text: 'Wehrmacht', isCorrect: false },
      { text: 'Kriegsmarine', isCorrect: false },
      { text: 'SS', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'germany', 'military'],
    createdAt: new Date('2024-02-27'),
  },
  {
    id: 'hist-ww2-14',
    category: 'History World War II',
    text: 'Which battle marked the first major defeat of the German army in World War II?',
    answers: [
      { text: 'Battle of Stalingrad', isCorrect: true },
      { text: 'Battle of Moscow', isCorrect: false },
      { text: 'Battle of Kursk', isCorrect: false },
      { text: 'Battle of Berlin', isCorrect: false },
    ],
    tags: ['history', 'world-war-ii', 'eastern-front', 'battles'],
    createdAt: new Date('2024-02-28'),
  },
];
