import { QuestionSeed } from '../types';

export const mathematicsBasic: QuestionSeed[] = [
  {
    id: 'math-basic-1',
    category: 'Mathematics Basic',
    text: 'What is 2+2?',
    answers: [
      { text: '3', isCorrect: false },
      { text: '4', isCorrect: true },
      { text: '5', isCorrect: false },
      { text: '6', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'arithmetic'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'math-basic-2',
    category: 'Mathematics Basic',
    text: 'Solve: 3x = 15',
    answers: [
      { text: '3', isCorrect: false },
      { text: '5', isCorrect: true },
      { text: '12', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'algebra'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'math-basic-3',
    category: 'Mathematics Basic',
    text: 'What is the value of π (pi)?',
    answers: [
      { text: '3.14', isCorrect: true },
      { text: '2.71', isCorrect: false },
      { text: '1.41', isCorrect: false },
      { text: '4.13', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'constants'],
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'math-basic-4',
    category: 'Mathematics Basic',
    text: 'What is the square root of 64?',
    answers: [
      { text: '6', isCorrect: false },
      { text: '7', isCorrect: false },
      { text: '8', isCorrect: true },
      { text: '9', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'square-root'],
    createdAt: new Date('2024-01-17'),
  },
  {
    id: 'math-basic-5',
    category: 'Mathematics Basic',
    text: 'Calculate: 15 × 4',
    answers: [
      { text: '50', isCorrect: false },
      { text: '60', isCorrect: true },
      { text: '70', isCorrect: false },
      { text: '80', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'multiplication'],
    createdAt: new Date('2024-01-18'),
  },
  {
    id: 'math-basic-6',
    category: 'Mathematics Basic',
    text: "What is the area of a circle with radius 5? (Use π = 3.14)",
    answers: [
      { text: '31.4', isCorrect: false },
      { text: '78.5', isCorrect: true },
      { text: '15.7', isCorrect: false },
      { text: '25', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'geometry', 'area'],
    createdAt: new Date('2024-01-19'),
  },
  {
    id: 'math-basic-7',
    category: 'Mathematics Basic',
    text: 'What is 25% of 80?',
    answers: [
      { text: '15', isCorrect: false },
      { text: '20', isCorrect: true },
      { text: '25', isCorrect: false },
      { text: '30', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'percentage'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'math-basic-8',
    category: 'Mathematics Basic',
    text: 'What is 1/2 + 1/4?',
    answers: [
      { text: '2/6', isCorrect: false },
      { text: '3/4', isCorrect: true },
      { text: '1/3', isCorrect: false },
      { text: '2/4', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'fractions'],
    createdAt: new Date('2024-01-21'),
  },
  {
    id: 'math-basic-9',
    category: 'Mathematics Basic',
    text: 'What is the perimeter of a rectangle with length 8 and width 5?',
    answers: [
      { text: '13', isCorrect: false },
      { text: '26', isCorrect: true },
      { text: '40', isCorrect: false },
      { text: '20', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'geometry', 'perimeter'],
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'math-basic-10',
    category: 'Mathematics Basic',
    text: 'What is 10² (10 squared)?',
    answers: [
      { text: '20', isCorrect: false },
      { text: '100', isCorrect: true },
      { text: '1000', isCorrect: false },
      { text: '10', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'exponents'],
    createdAt: new Date('2024-01-23'),
  },
  {
    id: 'math-basic-11',
    category: 'Mathematics Basic',
    text: 'Solve: 2x + 5 = 13',
    answers: [
      { text: '3', isCorrect: false },
      { text: '4', isCorrect: true },
      { text: '5', isCorrect: false },
      { text: '6', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'algebra'],
    createdAt: new Date('2024-01-24'),
  },
  {
    id: 'math-basic-12',
    category: 'Mathematics Basic',
    text: 'What is 144 ÷ 12?',
    answers: [
      { text: '10', isCorrect: false },
      { text: '11', isCorrect: false },
      { text: '12', isCorrect: true },
      { text: '13', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'division'],
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'math-basic-13',
    category: 'Mathematics Basic',
    text: 'What is the greatest common factor (GCF) of 12 and 18?',
    answers: [
      { text: '3', isCorrect: false },
      { text: '6', isCorrect: true },
      { text: '9', isCorrect: false },
      { text: '12', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'factors'],
    createdAt: new Date('2024-01-26'),
  },
  {
    id: 'math-basic-14',
    category: 'Mathematics Basic',
    text: 'What is 0.5 × 0.2?',
    answers: [
      { text: '0.1', isCorrect: true },
      { text: '0.7', isCorrect: false },
      { text: '1.0', isCorrect: false },
      { text: '0.3', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'decimals'],
    createdAt: new Date('2024-01-27'),
  },
  {
    id: 'math-basic-15',
    category: 'Mathematics Basic',
    text: 'What is the area of a triangle with base 6 and height 4?',
    answers: [
      { text: '10', isCorrect: false },
      { text: '12', isCorrect: true },
      { text: '24', isCorrect: false },
      { text: '20', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'geometry', 'area'],
    createdAt: new Date('2024-01-28'),
  },
  {
    id: 'math-basic-16',
    category: 'Mathematics Basic',
    text: 'What is 7 × 8?',
    answers: [
      { text: '54', isCorrect: false },
      { text: '56', isCorrect: true },
      { text: '58', isCorrect: false },
      { text: '60', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'multiplication'],
    createdAt: new Date('2024-01-29'),
  },
  {
    id: 'math-basic-17',
    category: 'Mathematics Basic',
    text: 'What is 3/4 as a decimal?',
    answers: [
      { text: '0.25', isCorrect: false },
      { text: '0.5', isCorrect: false },
      { text: '0.75', isCorrect: true },
      { text: '0.34', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'fractions', 'decimals'],
    createdAt: new Date('2024-01-30'),
  },
  {
    id: 'math-basic-18',
    category: 'Mathematics Basic',
    text: 'What is the least common multiple (LCM) of 4 and 6?',
    answers: [
      { text: '10', isCorrect: false },
      { text: '12', isCorrect: true },
      { text: '18', isCorrect: false },
      { text: '24', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'multiples'],
    createdAt: new Date('2024-01-31'),
  },
  {
    id: 'math-basic-19',
    category: 'Mathematics Basic',
    text: 'What is 15 - 7?',
    answers: [
      { text: '6', isCorrect: false },
      { text: '7', isCorrect: false },
      { text: '8', isCorrect: true },
      { text: '9', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'subtraction'],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'math-basic-20',
    category: 'Mathematics Basic',
    text: 'What is the perimeter of a square with side length 6?',
    answers: [
      { text: '12', isCorrect: false },
      { text: '24', isCorrect: true },
      { text: '36', isCorrect: false },
      { text: '18', isCorrect: false },
    ],
    tags: ['mathematics', 'basic', 'geometry', 'perimeter'],
    createdAt: new Date('2024-02-02'),
  },
];
